name: AstInvsee
version: 1.0
main: ru.asteris.Main
api-version: 1.16
authors: [Asteris]
commands:
  invsee:
    description: 'Открывает меню игрока'
  astinvsee:
    description: 'Настройка плагина'
permissions:
  astinvsee.use:
    default: op
  astinvsee.admin:
    default: op